# Generated by Django 5.0.1 on 2024-02-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_address_address_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
    ]
