# Generated by Django 5.0.1 on 2024-02-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_address_user_alter_address_zipcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
    ]
