# Generated by Django 5.0 on 2024-02-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_address_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
