# Generated by Django 5.0 on 2024-02-15 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0001_initial'),
        ('cart', '0001_initial'),
        ('user', '0011_address_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('total_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_status', models.CharField(default=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True), max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('confirmed', 'Order Confirmed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'cancelled'), ('returned', 'returned')], default='confirmed', max_length=20)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.address')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_side.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Orders',
                'ordering': ('-created',),
            },
        ),
    ]
