# Generated by Django 5.0 on 2024-02-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orderitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='cart',
        ),
    ]
