# Generated by Django 5.0 on 2024-02-29 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_wallet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.orderitem')),
                ('returned_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='cart.returnedproduct')),
            ],
        ),
    ]
