# Generated by Django 5.0.1 on 2024-03-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0005_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='coupon_name',
            new_name='coupon_code',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_value',
            new_name='discount_price',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='min_purchase_amount',
            new_name='minimum_amount',
        ),
    ]
