# Generated by Django 5.0.1 on 2024-03-17 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0007_alter_coupon_options_remove_coupon_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('strap_type', models.CharField(choices=[('metal', 'Metal Strap'), ('leather', 'Leather Strap'), ('steel', 'Steel Strap')], max_length=10)),
                ('image', models.ImageField(upload_to='product_variants')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.product')),
            ],
        ),
    ]
