# Generated by Django 5.0 on 2024-03-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0013_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
