# Generated by Django 5.0 on 2024-03-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0014_delete_banner_delete_chat_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prodents')),
            ],
        ),
    ]
